# ==== EPCAM–OCT4 Cellpose-SAM Pipeline Config (Single Model) ====

input_dir: "/scratch/brussel/vo/000/bvo00026/vsc11013/Projects/REGE-Nusa/Raw_data/Figure 3 panel D/VUB02"        # folder with your .czi images
output_dir: "/scratch/brussel/vo/000/bvo00026/vsc11013/Projects/REGE-Nusa/out"      # output folder (created if missing)

exclude_name_contains:
  - "zstack"
  - "orthogonal projection"
  - "overlay"
  - "overview"

# z-projection mode: "max" or "median"
z_strategy: "max"

cellpose:
  use_gpu: true
  epcam_model: "/scratch/brussel/vo/000/bvo00026/vsc11013/Projects/REGE-Nusa/models/cpsam_20q_cells"  # SAM model for EPCAM

save:
  projections: true
  zstack: false

quantify: true
analyzer_script: "/scratch/brussel/vo/000/bvo00026/vsc11013/Projects/REGE-Nusa/analysis.py"
